# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: courseprophet_development
  pool: 5
  username: courseprophet
  password: prophetcourse